#include "lib/exception.h"

std::unordered_map<Exception::ErrorType, std::string> Exception::errorMsg = {
  { ErrorType::INVALID_MAGIC, "Invalid binary magic code found. " },
  { ErrorType::INVALID_VER, "Invalid WebAssembly version code found. " },
  { ErrorType::INVALID_SECTION_ID, "Invalid Section id found. " },
  { ErrorType::INVALID_FUNC_TYPE, "Invalid Function type found. " },
  { ErrorType::INVALID_ELEM_TYPE, "Invalid element type found, only `anyfunc` allowed in MVP. " },
  { ErrorType::BAD_FSTREAM, "Bad input file stream found. " },
  { ErrorType::INVALID_GLOBAL_SIG, "Invalid global signature (global_type and init_expr) found. " },
  { ErrorType::MEM_EXCEED_MAX, "The amount of inital memory pages must be less than maximum. " },
  { ErrorType::MEM_DATA_EXCEED_MAX, "The initialized data exceed the memory size. " },  
  { ErrorType::TBL_EXCEED_MAX, "The amount of inital table entries must be less than maximum. " },
  { ErrorType::TBL_ELEM_EXCEED_MAX, "The initialized elements exceed the table entries. " },  
  { ErrorType::MEM_ACCESS_OOB, "Memory access out of bound. " },  
  { ErrorType::TBL_ACCESS_OOB, "Table access out of bound. " },  
  { ErrorType::MISSING_FUNC_PARAMS, "Insufficient values on stack for calling a function. " },
  { ErrorType::STACK_VAL_TYPE_MISMATCH, "Stack value type mismatch. " },
  { ErrorType::UNREACHABLE, "Unreachable. " },
  { ErrorType::ILLEGAL_LOCAL_IDX, "Illegal local index. " },  
  { ErrorType::EXHAUSTED_STACK_ACCESS, "No such available data on the stack. " },  
  { ErrorType::BREAK_LEVEL_EXCEEDED, "Break level exceeded. " },  
  { ErrorType::ARITY_TYPE_MISMATCH, "Arity type(s) mismatch. " },  
  { ErrorType::NO_ACTIV_ON_STACK, "No call frame on the stack. " },  
};
