name: Build CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch Codebase
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '10.x'
      - name: Setup C++ environment
        uses: kurocha/setup-cpp@v1
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run debug
